<<<<<<< HEAD
// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Replace this comment with your code
	}
}
=======
// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // Replace this comment with your code
	}
}
>>>>>>> 13fc53a2705d8c88f3994d4e5d1892bf07f9897a
