// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int n = Integer.parseInt(args[0]);
	double big = 0;
	double small = 0;
	int i = 0;
	while (i<n) 
	{
		double ran = Math.random();
		if (ran > 0.5) {
			big++;
		} else {
			small++;
		}
		i++;
	}
	if (big == 0 || small == 0) 
	{
	} 
	else {
		if (big > small) {
			System.out.println("Ratio: " + (small / big));
		}
		else {
			System.out.println("Ratio: " + (big / small));
		}
	}
	}
}
